### Getting all players who got NBA first, second, third team from BR and bringing it into one nice dataframe...

In [25]:
import pandas as pd
import os
import certifi 
import requests

from io import StringIO

all_nba_url = "https://www.basketball-reference.com/awards/all_league.html"

response = requests.get(
    all_nba_url,
    verify=certifi.where(),
    timeout=20
)

response.raise_for_status()

all_nba_tables = pd.read_html(StringIO(response.content.decode("utf-8")))

len(all_nba_tables)

1

In [26]:
all_nba = all_nba_tables[0]

all_nba.shape

(304, 9)

In [27]:
all_nba.head(25)

,Season,Lg,Tm,Voting,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,2025-26,NBA,1st,(V),Nikola Jokić C,Victor Wembanyama C,Shai Gilgeous-Alexander G,Luka Dončić G,Cade Cunningham G
1,2025-26,NBA,2nd,(V),Jaylen Brown F,Kawhi Leonard F,Kevin Durant F,Donovan Mitchell G,Jalen Brunson G
2,2025-26,NBA,3rd,(V),Jalen Duren C,Jalen Johnson F,Chet Holmgren F,Tyrese Maxey G,Jamal Murray G
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-25,NBA,1st,(V),Nikola Jokić C,Giannis Antetokounmpo F,Jayson Tatum F,Shai Gilgeous-Alexander G,Donovan Mitchell G
5,2024-25,NBA,2nd,(V),Evan Mobley C,LeBron James F,Stephen Curry G,Anthony Edwards G,Jalen Brunson G
6,2024-25,NBA,3rd,(V),Karl-Anthony Towns C,Jalen Williams F,Cade Cunningham G,Tyrese Haliburton G,James Harden G
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2023-24,NBA,1st,(V),Nikola Jokić C,Giannis Antetokounmpo F,Jayson Tatum F,Luka Dončić G,Shai Gilgeous-Alexander G
9,2023-24,NBA,2nd,(V),Anthony Davis C,Kevin Durant F,Kawhi Leonard F,Jalen Brunson G,Anthony Edwards G
10,2023-24,NBA,3rd,(V),LeBron James F,Domantas Sabonis F,Devin Booker G,Stephen Curry G,Tyrese Haliburton G
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2022-23,NBA,1st,(V),Joel Embiid C,Giannis Antetokounmpo F,Jayson Tatum F,Luka Dončić G,Shai Gilgeous-Alexander G
13,2022-23,NBA,2nd,(V),Nikola Jokić C,Jimmy Butler F,Jaylen Brown F,Donovan Mitchell G,Stephen Curry G
14,2022-23,NBA,3rd,(V),Domantas Sabonis C,LeBron James F,Julius Randle F,De'Aaron Fox G,Damian Lillard G
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021-22,NBA,1st,(V),Nikola Jokić C,Giannis Antetokounmpo F,Jayson Tatum F,Luka Dončić G,Devin Booker G
17,2021-22,NBA,2nd,(V),Joel Embiid C,Kevin Durant F,DeMar DeRozan F,Ja Morant G,Stephen Curry G
18,2021-22,NBA,3rd,(V),Karl-Anthony Towns C,LeBron James F,Pascal Siakam F,Chris Paul G,Trae Young G
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2020-21,NBA,1st,(V),Nikola Jokić C,Giannis Antetokounmpo F,Kawhi Leonard F,Stephen Curry G,Luka Dončić G
21,2020-21,NBA,2nd,(V),Joel Embiid C,Julius Randle F,LeBron James F,Chris Paul G,Damian Lillard G
22,2020-21,NBA,3rd,(V),Rudy Gobert C,Jimmy Butler F,Paul George F,Bradley Beal G,Kyrie Irving G
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2019-20,NBA,1st,(V),Anthony Davis C,Giannis Antetokounmpo F,LeBron James F,James Harden G,Luka Dončić G

In [28]:
all_nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Season      216 non-null    str
 1   Lg          216 non-null    str
 2   Tm          216 non-null    str
 3   Voting      158 non-null    str
 4   Unnamed: 4  216 non-null    str
 5   Unnamed: 5  216 non-null    str
 6   Unnamed: 6  216 non-null    str
 7   Unnamed: 7  216 non-null    str
 8   Unnamed: 8  216 non-null    str
dtypes: str(9)
memory usage: 21.5 KB

In [29]:
all_nba_clean1 = all_nba[all_nba["Season"].notna()].copy()

all_nba_clean1.head(25)

,Season,Lg,Tm,Voting,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,2025-26,NBA,1st,(V),Nikola Jokić C,Victor Wembanyama C,Shai Gilgeous-Alexander G,Luka Dončić G,Cade Cunningham G
1,2025-26,NBA,2nd,(V),Jaylen Brown F,Kawhi Leonard F,Kevin Durant F,Donovan Mitchell G,Jalen Brunson G
2,2025-26,NBA,3rd,(V),Jalen Duren C,Jalen Johnson F,Chet Holmgren F,Tyrese Maxey G,Jamal Murray G
4,2024-25,NBA,1st,(V),Nikola Jokić C,Giannis Antetokounmpo F,Jayson Tatum F,Shai Gilgeous-Alexander G,Donovan Mitchell G
5,2024-25,NBA,2nd,(V),Evan Mobley C,LeBron James F,Stephen Curry G,Anthony Edwards G,Jalen Brunson G
6,2024-25,NBA,3rd,(V),Karl-Anthony Towns C,Jalen Williams F,Cade Cunningham G,Tyrese Haliburton G,James Harden G
8,2023-24,NBA,1st,(V),Nikola Jokić C,Giannis Antetokounmpo F,Jayson Tatum F,Luka Dončić G,Shai Gilgeous-Alexander G
9,2023-24,NBA,2nd,(V),Anthony Davis C,Kevin Durant F,Kawhi Leonard F,Jalen Brunson G,Anthony Edwards G
10,2023-24,NBA,3rd,(V),LeBron James F,Domantas Sabonis F,Devin Booker G,Stephen Curry G,Tyrese Haliburton G
12,2022-23,NBA,1st,(V),Joel Embiid C,Giannis Antetokounmpo F,Jayson Tatum F,Luka Dončić G,Shai Gilgeous-Alexander G
13,2022-23,NBA,2nd,(V),Nikola Jokić C,Jimmy Butler F,Jaylen Brown F,Donovan Mitchell G,Stephen Curry G
14,2022-23,NBA,3rd,(V),Domantas Sabonis C,LeBron James F,Julius Randle F,De'Aaron Fox G,Damian Lillard G
16,2021-22,NBA,1st,(V),Nikola Jokić C,Giannis Antetokounmpo F,Jayson Tatum F,Luka Dončić G,Devin Booker G
17,2021-22,NBA,2nd,(V),Joel Embiid C,Kevin Durant F,DeMar DeRozan F,Ja Morant G,Stephen Curry G
18,2021-22,NBA,3rd,(V),Karl-Anthony Towns C,LeBron James F,Pascal Siakam F,Chris Paul G,Trae Young G
20,2020-21,NBA,1st,(V),Nikola Jokić C,Giannis Antetokounmpo F,Kawhi Leonard F,Stephen Curry G,Luka Dončić G
21,2020-21,NBA,2nd,(V),Joel Embiid C,Julius Randle F,LeBron James F,Chris Paul G,Damian Lillard G
22,2020-21,NBA,3rd,(V),Rudy Gobert C,Jimmy Butler F,Paul George F,Bradley Beal G,Kyrie Irving G
24,2019-20,NBA,1st,(V),Anthony Davis C,Giannis Antetokounmpo F,LeBron James F,James Harden G,Luka Dončić G
25,2019-20,NBA,2nd,(V),Nikola Jokić C,Kawhi Leonard F,Pascal Siakam F,Damian Lillard G,Chris Paul G
26,2019-20,NBA,3rd,(V),Rudy Gobert C,Jayson Tatum F,Jimmy Butler F,Ben Simmons G,Russell Westbrook G
28,2018-19,NBA,1st,(V),Nikola Jokić C,Giannis Antetokounmpo F,Paul George F,James Harden G,Stephen Curry G
29,2018-19,NBA,2nd,(V),Joel Embiid C,Kevin Durant F,Kawhi Leonard F,Damian Lillard G,Kyrie Irving G
30,2018-19,NBA,3rd,(V),Rudy Gobert C,LeBron James F,Blake Griffin F,Kemba Walker G,Russell Westbrook G
32,2017-18,NBA,1st,(V),Anthony Davis C,LeBron James F,Kevin Durant F,Damian Lillard G,James Harden G

In [30]:
new_column_names = ["season", "league", "team", "vote", "center", "power_forward", "small_forward", "shooting_guard", "point_guard"]

all_nba_clean1.columns = new_column_names

all_nba_clean1.head()

,season,league,team,vote,center,power_forward,small_forward,shooting_guard,point_guard
0,2025-26,NBA,1st,(V),Nikola Jokić C,Victor Wembanyama C,Shai Gilgeous-Alexander G,Luka Dončić G,Cade Cunningham G
1,2025-26,NBA,2nd,(V),Jaylen Brown F,Kawhi Leonard F,Kevin Durant F,Donovan Mitchell G,Jalen Brunson G
2,2025-26,NBA,3rd,(V),Jalen Duren C,Jalen Johnson F,Chet Holmgren F,Tyrese Maxey G,Jamal Murray G
4,2024-25,NBA,1st,(V),Nikola Jokić C,Giannis Antetokounmpo F,Jayson Tatum F,Shai Gilgeous-Alexander G,Donovan Mitchell G
5,2024-25,NBA,2nd,(V),Evan Mobley C,LeBron James F,Stephen Curry G,Anthony Edwards G,Jalen Brunson G

In [31]:
all_nba_clean2 = all_nba_clean1[["season", "team", "center", "power_forward", "small_forward", "shooting_guard", "point_guard"]]

all_nba_clean2.head()

,season,team,center,power_forward,small_forward,shooting_guard,point_guard
0,2025-26,1st,Nikola Jokić C,Victor Wembanyama C,Shai Gilgeous-Alexander G,Luka Dončić G,Cade Cunningham G
1,2025-26,2nd,Jaylen Brown F,Kawhi Leonard F,Kevin Durant F,Donovan Mitchell G,Jalen Brunson G
2,2025-26,3rd,Jalen Duren C,Jalen Johnson F,Chet Holmgren F,Tyrese Maxey G,Jamal Murray G
4,2024-25,1st,Nikola Jokić C,Giannis Antetokounmpo F,Jayson Tatum F,Shai Gilgeous-Alexander G,Donovan Mitchell G
5,2024-25,2nd,Evan Mobley C,LeBron James F,Stephen Curry G,Anthony Edwards G,Jalen Brunson G

In [32]:
all_nba_long = pd.melt(all_nba_clean2,
id_vars = ["season", "team"],
value_vars = ["center", "power_forward", "small_forward", "shooting_guard", "point_guard"],
var_name = "position",
value_name = "player_name")

all_nba_long.head(30)

     season team position           player_name
0   2025-26  1st   center        Nikola Jokić C
1   2025-26  2nd   center        Jaylen Brown F
2   2025-26  3rd   center         Jalen Duren C
3   2024-25  1st   center        Nikola Jokić C
4   2024-25  2nd   center         Evan Mobley C
5   2024-25  3rd   center  Karl-Anthony Towns C
6   2023-24  1st   center        Nikola Jokić C
7   2023-24  2nd   center       Anthony Davis C
8   2023-24  3rd   center        LeBron James F
9   2022-23  1st   center         Joel Embiid C
10  2022-23  2nd   center        Nikola Jokić C
11  2022-23  3rd   center    Domantas Sabonis C
12  2021-22  1st   center        Nikola Jokić C
13  2021-22  2nd   center         Joel Embiid C
14  2021-22  3rd   center  Karl-Anthony Towns C
15  2020-21  1st   center        Nikola Jokić C
16  2020-21  2nd   center         Joel Embiid C
17  2020-21  3rd   center         Rudy Gobert C
18  2019-20  1st   center       Anthony Davis C
19  2019-20  2nd   center        Nikola Jokić C
20  2019-20  3rd   center         Rudy Gobert C
21  2018-19  1st   center        Nikola Jokić C
22  2018-19  2nd   center         Joel Embiid C
23  2018-19  3rd   center         Rudy Gobert C
24  2017-18  1st   center       Anthony Davis C
25  2017-18  2nd   center         Joel Embiid C
26  2017-18  3rd   center  Karl-Anthony Towns C
27  2016-17  1st   center       Anthony Davis C
28  2016-17  2nd   center         Rudy Gobert C
29  2016-17  3rd   center      DeAndre Jordan C

In [33]:
all_nba_long = all_nba_long[all_nba_long["season"].str[:4].astype(int).between(2000,2025)].copy()

all_nba_long.shape

(390, 4)

In [34]:
all_nba_long.tail()

      season team     position      player_name
937  2001-02  2nd  point_guard    Gary Payton G
938  2001-02  3rd  point_guard    Paul Pierce G
939  2000-01  1st  point_guard     Jason Kidd G
940  2000-01  2nd  point_guard  Tracy McGrady G
941  2000-01  3rd  point_guard    Gary Payton G

In [35]:
all_nba_long["source_slot"] = all_nba_long["position"].map({
    "center": 1,
    "power_forward": 2,
    "small_forward": 3,
    "shooting_guard": 4,
    "point_guard": 5
})

all_nba_long["player_position"] = (
    all_nba_long["player_name"].str.extract(r"\s([CFG])$")
)

all_nba_long["player_name"] = (
    all_nba_long["player_name"]
    .str.replace(r"\s+[CFG]$", "", regex=True)
    .str.strip()
)

all_nba_long.head()

    season team position   player_name  source_slot player_position
0  2025-26  1st   center  Nikola Jokić            1               C
1  2025-26  2nd   center  Jaylen Brown            1               F
2  2025-26  3rd   center   Jalen Duren            1               C
3  2024-25  1st   center  Nikola Jokić            1               C
4  2024-25  2nd   center   Evan Mobley            1               C

In [36]:
all_nba_long["season"] = (
    all_nba_long["season"].str[:5]
    + "20"
    + all_nba_long["season"].str[-2:]
)

all_nba_long["all_nba_team"] = (
    all_nba_long["team"].map({
        "1st": 1,
        "2nd": 2,
        "3rd": 3
    })
)

all_nba_long["award_type"] = "All-NBA"

all_nba_long.head(25)

,season,team,position,player_name,source_slot,player_position,all_nba_team,award_type
0,2025-2026,1st,center,Nikola Jokić,1,C,1,All-NBA
1,2025-2026,2nd,center,Jaylen Brown,1,F,2,All-NBA
2,2025-2026,3rd,center,Jalen Duren,1,C,3,All-NBA
3,2024-2025,1st,center,Nikola Jokić,1,C,1,All-NBA
4,2024-2025,2nd,center,Evan Mobley,1,C,2,All-NBA
5,2024-2025,3rd,center,Karl-Anthony Towns,1,C,3,All-NBA
6,2023-2024,1st,center,Nikola Jokić,1,C,1,All-NBA
7,2023-2024,2nd,center,Anthony Davis,1,C,2,All-NBA
8,2023-2024,3rd,center,LeBron James,1,F,3,All-NBA
9,2022-2023,1st,center,Joel Embiid,1,C,1,All-NBA
10,2022-2023,2nd,center,Nikola Jokić,1,C,2,All-NBA
11,2022-2023,3rd,center,Domantas Sabonis,1,C,3,All-NBA
12,2021-2022,1st,center,Nikola Jokić,1,C,1,All-NBA
13,2021-2022,2nd,center,Joel Embiid,1,C,2,All-NBA
14,2021-2022,3rd,center,Karl-Anthony Towns,1,C,3,All-NBA
15,2020-2021,1st,center,Nikola Jokić,1,C,1,All-NBA
16,2020-2021,2nd,center,Joel Embiid,1,C,2,All-NBA
17,2020-2021,3rd,center,Rudy Gobert,1,C,3,All-NBA
18,2019-2020,1st,center,Anthony Davis,1,C,1,All-NBA
19,2019-2020,2nd,center,Nikola Jokić,1,C,2,All-NBA
20,2019-2020,3rd,center,Rudy Gobert,1,C,3,All-NBA
21,2018-2019,1st,center,Nikola Jokić,1,C,1,All-NBA
22,2018-2019,2nd,center,Joel Embiid,1,C,2,All-NBA
23,2018-2019,3rd,center,Rudy Gobert,1,C,3,All-NBA
24,2017-2018,1st,center,Anthony Davis,1,C,1,All-NBA

In [37]:
all_nba_final = all_nba_long[
    ["season", "all_nba_team", "player_name", "player_position"]
].copy()

all_nba_final.shape

(390, 4)

In [38]:
all_nba_final.head()

      season  all_nba_team   player_name player_position
0  2025-2026             1  Nikola Jokić               C
1  2025-2026             2  Jaylen Brown               F
2  2025-2026             3   Jalen Duren               C
3  2024-2025             1  Nikola Jokić               C
4  2024-2025             2   Evan Mobley               C

In [39]:
all_nba_final.info()

<class 'pandas.DataFrame'>
Index: 390 entries, 0 to 941
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   season           390 non-null    str
 1   all_nba_team     390 non-null    int64
 2   player_name      390 non-null    str
 3   player_position  390 non-null    str
dtypes: int64(1), str(3)
memory usage: 15.2 KB

In [40]:
staging_dir = "data/staging/awards/S14A_all_nba"

os.makedirs(staging_dir, exist_ok=True)

In [41]:
all_nba_final.to_csv(
    f"{staging_dir}/S14A_all_nba.csv",
    index=False,
    encoding="utf-8"
)